In [1]:
import pandas as pd

### Loading data premier league matches for 3 seasons

In [2]:
file_match = "match_premier_league.csv"

In [3]:
matches = pd.read_csv(file_match, index_col=0)

In [4]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,Match Report,NaN,18.0,4.0,16.9,1.0,0.0,0.0,2022,Manchester City
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,Match Report,NaN,16.0,4.0,17.3,1.0,0.0,0.0,2022,Manchester City
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,Match Report,NaN,25.0,10.0,14.3,0.0,0.0,0.0,2022,Manchester City
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,Match Report,NaN,25.0,8.0,14.0,0.0,0.0,0.0,2022,Manchester City
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,Match Report,NaN,16.0,1.0,15.7,1.0,0.0,0.0,2022,Manchester City

### Investigating missing data
we know that in one season there is 38 matches for each team. So the total numbers of matches should be 2280

In [5]:
matches.shape

(2112, 27)

In [6]:
matches["team"].value_counts()

Manchester City             113
Newcastle United            113
Burnley                     113
Liverpool                   113
Southampton                 113
Aston Villa                 113
Crystal Palace              113
Everton                     113
Wolverhampton Wanderers     113
Manchester United           113
Arsenal                     113
Tottenham Hotspur           113
Chelsea                     113
Leicester City               76
West Ham United              76
Brighton and Hove Albion     76
Sheffield United             76
Leeds United                 75
Watford                      75
Fulham                       38
West Bromwich Albion         38
Bournemouth                  38
Norwich City                 38
Brentford                    37
Name: team, dtype: int64

In [13]:
matches[matches['team']== 'Leicester City']

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2020-09-13,14:00,Premier League,Matchweek 1,Sun,Away,W,3.0,0.0,West Brom,...,Match Report,NaN,11.0,5.0,19.2,1.0,2.0,2.0,2021,Leicester City
1,2020-09-20,19:00,Premier League,Matchweek 2,Sun,Home,W,4.0,2.0,Burnley,...,Match Report,NaN,12.0,6.0,15.9,0.0,0.0,0.0,2021,Leicester City
3,2020-09-27,16:30,Premier League,Matchweek 3,Sun,Away,W,5.0,2.0,Manchester City,...,Match Report,NaN,4.0,4.0,27.5,0.0,3.0,3.0,2021,Leicester City
4,2020-10-04,12:00,Premier League,Matchweek 4,Sun,Home,L,0.0,3.0,West Ham,...,Match Report,NaN,4.0,0.0,17.5,0.0,0.0,0.0,2021,Leicester City
5,2020-10-18,19:15,Premier League,Matchweek 5,Sun,Home,L,0.0,1.0,Aston Villa,...,Match Report,NaN,11.0,5.0,18.9,2.0,0.0,0.0,2021,Leicester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,2020-07-07,20:15,Premier League,Matchweek 34,Tue,Away,D,1.0,1.0,Arsenal,...,Match Report,NaN,13.0,5.0,20.0,1.0,0.0,0.0,2020,Leicester City
44,2020-07-12,19:00,Premier League,Matchweek 35,Sun,Away,L,1.0,4.0,Bournemouth,...,Match Report,NaN,13.0,5.0,17.4,0.0,0.0,0.0,2020,Leicester City
45,2020-07-16,18:00,Premier League,Matchweek 36,Thu,Home,W,2.0,0.0,Sheffield Utd,...,Match Report,NaN,15.0,7.0,15.8,0.0,0.0,0.0,2020,Leicester City
46,2020-07-19,16:00,Premier League,Matchweek 37,Sun,Away,L,0.0,3.0,Tottenham,...,Match Report,NaN,24.0,6.0,17.8,2.0,0.0,0.0,2020,Leicester City
47,2020-07-26,16:00,Premier League,Matchweek 38,Sun,Home,L,0.0,2.0,Manchester Utd,...,Match Report,NaN,14.0,3.0,16.1,1.0,0.0,0.0,2020,Leicester City

In [14]:
matches["round"].value_counts()

Matchweek 28    56
Matchweek 14    56
Matchweek 4     56
Matchweek 29    56
Matchweek 12    56
Matchweek 2     56
Matchweek 23    56
Matchweek 17    56
Matchweek 5     56
Matchweek 22    56
Matchweek 20    56
Matchweek 24    56
Matchweek 7     56
Matchweek 13    56
Matchweek 10    56
Matchweek 26    56
Matchweek 15    56
Matchweek 11    56
Matchweek 31    56
Matchweek 35    56
Matchweek 21    56
Matchweek 6     56
Matchweek 25    56
Matchweek 8     56
Matchweek 19    56
Matchweek 27    56
Matchweek 18    56
Matchweek 1     56
Matchweek 3     56
Matchweek 30    56
Matchweek 37    56
Matchweek 36    56
Matchweek 16    56
Matchweek 34    56
Matchweek 9     56
Matchweek 33    56
Matchweek 32    56
Matchweek 38    40
Name: round, dtype: int64

### Cleaning our data for Machine Learning

In [15]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [16]:
matches["date"]= pd.to_datetime(matches["date"])

In [17]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                     float64
ga                     float64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

### Creating predictors for Machine Learning

In [23]:
matches["venue_code"]=matches["venue"].astype("category").cat.codes

In [25]:
matches["opp_code"]=matches["opponent"].astype("category").cat.codes

In [27]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [30]:
matches["day_code"]=matches["date"].dt.dayofweek

In [119]:
matches["target"] = (matches["result"]== "W").astype("int")

In [120]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2021-08-15,16:30,Premier League,Matchweek 1,Sun,Away,L,0.0,1.0,Tottenham,...,1.0,0.0,0.0,2022,Manchester City,0,19,16,6,0
2,2021-08-21,15:00,Premier League,Matchweek 2,Sat,Home,W,5.0,0.0,Norwich City,...,1.0,0.0,0.0,2022,Manchester City,1,16,15,5,1
3,2021-08-28,12:30,Premier League,Matchweek 3,Sat,Home,W,5.0,0.0,Arsenal,...,0.0,0.0,0.0,2022,Manchester City,1,0,12,5,1
4,2021-09-11,15:00,Premier League,Matchweek 4,Sat,Away,W,1.0,0.0,Leicester City,...,0.0,0.0,0.0,2022,Manchester City,0,11,15,5,1
6,2021-09-18,15:00,Premier League,Matchweek 5,Sat,Home,D,0.0,0.0,Southampton,...,1.0,0.0,0.0,2022,Manchester City,1,18,15,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2020-07-07,18:00,Premier League,Matchweek 34,Tue,Away,L,1.0,2.0,Watford,...,1.0,0.0,0.0,2020,Norwich City,0,20,18,1,0
39,2020-07-11,12:30,Premier League,Matchweek 35,Sat,Home,L,0.0,4.0,West Ham,...,1.0,0.0,0.0,2020,Norwich City,1,22,12,5,0
40,2020-07-14,20:15,Premier League,Matchweek 36,Tue,Away,L,0.0,1.0,Chelsea,...,0.0,0.0,0.0,2020,Norwich City,0,6,20,1,0
41,2020-07-18,17:30,Premier League,Matchweek 37,Sat,Home,L,0.0,2.0,Burnley,...,0.0,0.0,0.0,2020,Norwich City,1,5,17,5,0
42,2020-07-26,16:00,Premier League,Matchweek 38,Sun,Away,L,0.0,5.0,Manchester City,...,0.0,0.0,0.0,2020,Norwich City,0,13,16,6,0

In [121]:
from sklearn.ensemble import RandomForestClassifier

In [122]:
rf=RandomForestClassifier(n_estimators=10, min_samples_split=10, random_state=1)

In [123]:
matches['date'].unique

<bound method Series.unique of 1    2021-08-15
2    2021-08-21
3    2021-08-28
4    2021-09-11
6    2021-09-18
        ...
38   2020-07-07
39   2020-07-11
40   2020-07-14
41   2020-07-18
42   2020-07-26
Name: date, Length: 2112, dtype: datetime64[ns]>

In [124]:
train = matches[matches['date'] < '2022-01-01']

In [125]:
test = matches[matches['date'] >= '2022-01-01']

In [126]:
len(test)

300

In [127]:
len(train)

1812

In [128]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [129]:
rf.fit(train[predictors], train['target'])

RandomForestClassifier(min_samples_split=10, n_estimators=10, random_state=1)

In [130]:
preds = rf.predict(test[predictors])

In [131]:
preds

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0])

In [132]:
from sklearn.metrics import accuracy_score

In [133]:
acc = accuracy_score(test["target"], preds)

In [134]:
acc

0.5966666666666667

In [135]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [137]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           144  30
1            91  35

In [138]:
from sklearn.metrics import precision_score

In [139]:
precision_score(test["target"], preds) #the ability of the classifier not to label as positive a sample that is negative

0.5384615384615384

In [140]:
144/(144+91) #specificity moins de faux nÃ©gatif (the ability of the classifier to avoid all the negative samples.)

0.6127659574468085

In [141]:
35/(35+30) #ppv

0.5384615384615384

In [144]:
35/(35+91) #sensitivity plus de faux positif (the ability of the classifier to find all the positive samples.)

0.2777777777777778

### Improving precision with roling average

In [145]:
grouped_matches = matches.groupby("team")

In [146]:
group = grouped_matches.get_group("Manchester City").sort_values("date")

In [147]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2019-08-10,12:30,Premier League,Matchweek 1,Sat,Away,W,5.0,0.0,West Ham,...,0.0,1.0,1.0,2020,Manchester City,0,22,12,5,1
2,2019-08-17,17:30,Premier League,Matchweek 2,Sat,Home,D,2.0,2.0,Tottenham,...,0.0,0.0,0.0,2020,Manchester City,1,19,17,5,0
3,2019-08-25,14:00,Premier League,Matchweek 3,Sun,Away,W,3.0,1.0,Bournemouth,...,0.0,0.0,0.0,2020,Manchester City,0,2,14,6,1
4,2019-08-31,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,0.0,Brighton,...,1.0,0.0,0.0,2020,Manchester City,1,4,15,5,1
5,2019-09-14,17:30,Premier League,Matchweek 5,Sat,Away,L,2.0,3.0,Norwich City,...,0.0,0.0,0.0,2020,Manchester City,0,16,17,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,0.0,1.0,1.0,2022,Manchester City,1,20,15,5,1
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4.0,0.0,Leeds United,...,0.0,0.0,0.0,2022,Manchester City,0,10,17,5,1
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5.0,0.0,Newcastle Utd,...,1.0,0.0,0.0,2022,Manchester City,1,15,16,6,1
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5.0,1.0,Wolves,...,0.0,0.0,0.0,2022,Manchester City,0,23,20,2,1
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2.0,2.0,West Ham,...,2.0,0.0,1.0,2022,Manchester City,0,22,14,6,0

In [148]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [149]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
4,2019-08-31,15:00,Premier League,Matchweek 4,Sat,Home,W,4.0,0.0,Brighton,...,5,1,3.333333,1.000000,19.666667,7.000000,14.866667,0.000000,0.333333,0.333333
5,2019-09-14,17:30,Premier League,Matchweek 5,Sat,Away,L,2.0,3.0,Norwich City,...,5,0,3.000000,1.000000,20.333333,6.333333,14.733333,0.333333,0.000000,0.000000
7,2019-09-21,15:00,Premier League,Matchweek 6,Sat,Home,W,8.0,0.0,Watford,...,5,1,3.000000,1.333333,19.000000,6.333333,14.333333,0.333333,0.000000,0.000000
9,2019-09-28,17:30,Premier League,Matchweek 7,Sat,Away,W,3.0,1.0,Everton,...,5,1,4.666667,1.000000,22.666667,8.333333,14.300000,1.000000,0.333333,0.333333
11,2019-10-06,14:00,Premier League,Matchweek 8,Sun,Home,L,0.0,2.0,Wolves,...,6,0,4.333333,1.333333,24.333333,9.666667,13.800000,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2022-04-23,15:00,Premier League,Matchweek 34,Sat,Home,W,5.0,1.0,Watford,...,5,1,2.333333,0.666667,15.333333,5.000000,17.200000,0.333333,0.000000,0.000000
52,2022-04-30,17:30,Premier League,Matchweek 35,Sat,Away,W,4.0,0.0,Leeds United,...,5,1,3.333333,1.000000,16.000000,5.333333,16.700000,0.333333,0.333333,0.333333
54,2022-05-08,16:30,Premier League,Matchweek 36,Sun,Home,W,5.0,0.0,Newcastle Utd,...,6,1,4.000000,0.333333,18.666667,6.000000,16.333333,0.000000,0.333333,0.333333
55,2022-05-11,20:15,Premier League,Matchweek 33,Wed,Away,W,5.0,1.0,Wolves,...,2,1,4.666667,0.333333,20.000000,7.333333,15.166667,0.333333,0.333333,0.333333
56,2022-05-15,14:00,Premier League,Matchweek 37,Sun,Away,D,2.0,2.0,West Ham,...,6,0,4.666667,0.333333,18.333333,6.666667,14.933333,0.333333,0.000000,0.000000

In [150]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [151]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 3  2019-09-01  16:30  Premier League   Matchweek 4
                        4  2019-09-15  16:30  Premier League   Matchweek 5
                        6  2019-09-22  16:30  Premier League   Matchweek 6
                        8  2019-09-30  20:00  Premier League   Matchweek 7
                        10 2019-10-06  14:00  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 36 2022-04-24  14:00  Premier League  Matchweek 34
                        37 2022-04-30  15:00  Premier League  Matchweek 35
                        38 2022-05-07  15:00  Premier League  Matchweek 36
                        39 2022-05-11  20:15  Premier League  Matchweek 33
                        40 2022-05-15  14:00  Premier League  Matchweek 37

                            day venue result   gf   ga         opponent  ...  \
team                                                                     ...
Arsenal                 3   Sun  Home      D  2.0  2.0        Tottenham  ...
                        4   Sun  Away      D  2.0  2.0          Watford  ...
                        6   Sun  Home      W  3.0  2.0      Aston Villa  ...
                        8   Mon  Away      D  1.0  1.0   Manchester Utd  ...
                        10  Sun  Home      W  1.0  0.0      Bournemouth  ...
...                         ...   ...    ...  ...  ...              ...  ...
Wolverhampton Wanderers 36  Sun  Away      L  0.0  1.0          Burnley  ...
                        37  Sat  Home      L  0.0  3.0         Brighton  ...
                        38  Sat  Away      D  2.0  2.0          Chelsea  ...
                        39  Wed  Home      L  1.0  5.0  Manchester City  ...
                        40  Sun  Home      D  1.0  1.0     Norwich City  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 3          6       0    1.333333    1.333333
                        4          6       0    1.666667    2.000000
                        6          6       1    1.666667    2.333333
                        8          0       0    2.333333    2.000000
                        10         6       1    2.000000    1.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 36         6       0    1.333333    1.666667
                        37         5       0    0.666667    1.000000
                        38         5       0    0.000000    1.666667
                        39         2       0    0.666667    2.000000
                        40         6       0    1.000000    3.333333

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 3   10.666667    4.666667    17.133333   0.333333
                        4   17.000000    6.666667    18.366667   1.000000
                        6   14.000000    5.000000    19.400000   1.000000
                        8   17.666667    5.333333    18.433333   1.333333
                        10  12.333333    4.333333    18.100000   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 36  10.000000    4.666667    17.633333   0.000000
                        37   8.666667    3.333333    16.966667   0.000000
                        38   8.666667    2.333333    18.233333   0.333333
                        39  11.666667    3.000000    17.133333   0.333333
                        40  10.666667    2.666667    16.400000   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 3     0.000000       0.000000
                        4     0.000000       0.000000
                        6     0.000000       0.000000
                        8     0.333333       0.333333
                        10    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 36    0.000000       0.000000
                        37    0.000000       0.000000
                        38    0.000000       0.000000
                        39    0.000000       0.000000
                        40    0.000000       0.000000

[2037 rows x 40 columns]

In [152]:
matches_rolling = matches_rolling.droplevel('team')

In [154]:
matches_rolling.index = range(matches_rolling.shape[0])

In [155]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [156]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [157]:
error

0.5753424657534246

In [158]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [159]:
combined.head(10)

     actual  predicted       date     team        opponent result
93        0          1 2022-01-23  Arsenal         Burnley      D
94        1          1 2022-02-10  Arsenal          Wolves      W
95        1          1 2022-02-19  Arsenal       Brentford      W
96        1          0 2022-02-24  Arsenal          Wolves      W
97        1          1 2022-03-06  Arsenal         Watford      W
98        1          0 2022-03-13  Arsenal  Leicester City      W
99        0          0 2022-03-16  Arsenal       Liverpool      L
100       1          0 2022-03-19  Arsenal     Aston Villa      W
101       0          0 2022-04-04  Arsenal  Crystal Palace      L
102       0          0 2022-04-09  Arsenal        Brighton      L

In [160]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [161]:
combined["new_team"] = combined["team"].map(mapping)

In [162]:
combined

,actual,predicted,date,team,opponent,result,new_team
93,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal
94,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal
95,1,1,2022-02-19,Arsenal,Brentford,W,Arsenal
96,1,0,2022-02-24,Arsenal,Wolves,W,Arsenal
97,1,1,2022-03-06,Arsenal,Watford,W,Arsenal
...,...,...,...,...,...,...,...
2032,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves
2033,0,1,2022-04-30,Wolverhampton Wanderers,Brighton,L,Wolves
2034,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves
2035,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves
2036,0,0,2022-05-15,Wolverhampton Wanderers,Norwich City,D,Wolves

In [163]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [164]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2022-01-23,Arsenal,Burnley,D,Arsenal,0,0,Burnley,Arsenal,D,Burnley
1,1,1,2022-02-10,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
2,1,1,2022-02-19,Arsenal,Brentford,W,Arsenal,0,0,Brentford,Arsenal,L,Brentford
3,1,0,2022-02-24,Arsenal,Wolves,W,Arsenal,0,0,Wolverhampton Wanderers,Arsenal,L,Wolves
4,1,1,2022-03-06,Arsenal,Watford,W,Arsenal,0,0,Watford,Arsenal,L,Watford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,1,0,2022-04-02,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
230,0,0,2022-04-08,Wolverhampton Wanderers,Newcastle Utd,L,Wolves,1,0,Newcastle United,Wolves,W,Newcastle Utd
231,0,0,2022-04-24,Wolverhampton Wanderers,Burnley,L,Wolves,1,0,Burnley,Wolves,W,Burnley
232,0,0,2022-05-07,Wolverhampton Wanderers,Chelsea,D,Wolves,0,0,Chelsea,Wolves,D,Chelsea
233,0,0,2022-05-11,Wolverhampton Wanderers,Manchester City,L,Wolves,1,1,Manchester City,Wolves,W,Manchester City

In [165]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

1    29
0    23
Name: actual_x, dtype: int64